---
- name: Install Docker and Docker compose Stack
  hosts: all
  become: true

  tasks:
    - name: Initialize base apt package cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true

    - name: Download official Docker installation script
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: "0755"

    # CHANGE: Swapped ansible.builtin.shell for ansible.builtin.command
    - name: Execute Docker installation script
      ansible.builtin.command: sh /tmp/get-docker.sh
      register: script_output
      changed_when: true

    - name: Ensure Docker service is running and enabled on boot
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true
