---
- name: Install Docker and Docker compose Stack
  hosts: all
  become: true

  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Enable universe repository
      ansible.builtin.apt_repository:
        repo: eb http://archive.ubuntu.com/ubuntu jammy universe
        state: present

    - name: Update apt cache after enabling universe
      ansible.builtin.apt:
        update_cache: true

    - name: Install required system dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - python3-docker
        state: present

    - name: Add Docker GPG apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository to APT sources
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Install Docker Engine and CLI binaries
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: true

    - name: Ensure Docker service is running and enabled on boot
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Install Python Docker SDK required by Ansible Docker modules
      ansible.builtin.pip:
        name: docker
        state: present
